config/routes.rb
Site::Application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :sessions => "sessions", :registrations => "registrations" } do
      get 'sign_in', :to => 'users/sessions#new', :as => :new_user_session
      match "/signout" => "sessions#destroy", :as => :signout
  end
  
  resources :application do 
    collection do
      get 'get_static'
      get 'extra'
    end
  end

   root :to => 'application#index'

end

app/models/position.rb
class Position < ActiveRecord::Base
  attr_accessible :name, :left, :top
  
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and 
  devise :database_authenticatable, :registerable,:token_authenticatable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable

  has_many :positions, :dependent => :destroy

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
  
   def self.find_for_facebook_oauth(access_token)
     data = access_token['extra']['raw_info']
     if user = User.find_by_email(data["email"])
       user
     else # Create an user with a stub password.
       user = User.new
       user.email =  data["email"]
       user.password = Devise.friendly_token[0,20]
       user.skip_confirmation!
      if user.save
        user
      else
      end
     end
   end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :authenticate_user!, :only => [""]
  before_filter :load_layout, :only => [:index]
  
  
  def index
  end
  
  def get_static
     if template_exists? path = 'application/' + params[:id]
       render :template => path, :layout => false
     else
       render :template => 'application/index', :layout => false
     end
  end
  
  def extra
    status = ""
    if current_user && !params.blank?
      pos = Position.where(:user_id => current_user.id, :name => params[:name])
      unless pos.blank?
        position = Position.find(pos[0].id)
        position.update_attributes(:left => params[:left], :top => params[:top])
      else
       current_user.positions.create(:name => params[:name], :left => params[:left], :top => params[:top])
      end
      status = "success"
    else
      status = "fail"
    end
    render :json => status.to_json
  end
  
  def after_sign_in_path_for(resource)
   logger.debug "\n\n\n##### #{root_path}\n\n"
   logger.debug "\n\n\n##### #{request.referer}\n\n"
   root_path
  end
  
  
  private
    def load_layout
      if current_user
        if params[:layout]
          current_user ? current_user.update_attribute(:layout, params[:layout]) : ""
          render :layout => params[:layout]
        else
          render :layout => current_user.layout.blank? ? "new_layout" : current_user.layout 
        end
      else
        if params[:layout]
          render :layout => params[:layout]
        else
          render :layout => 'new_layout'
        end
      end
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  before_filter :load_layout, :except => :create
  
  def new
  end
  
  def create
    super
  end
  
  private
    def load_layout
      if current_user
        if params[:layout]
          current_user ? current_user.update_attribute(:layout, params[:layout]) : ""
          render :layout => params[:layout]
        else
          render :layout => current_user.layout
        end
      else
        if params[:layout] && params[:layout] != "false"
          render :layout => params[:layout]
        else
          render :layout => 'new_layout'
        end
      end
    end
end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController
  
  before_filter :load_layout, :except => [:create, :destroy]
  
  def new
  
  end
   
  def destroy
    super
  end
  
  private
    def load_layout
      if current_user
        if params[:layout]
          current_user ? current_user.update_attribute(:layout, params[:layout]) : ""
          render :layout => params[:layout]
        else
          render :layout => current_user.layout
        end
      else
        if params[:layout]
          render :layout => params[:layout]
        else
          render :layout => 'new_layout'
        end
      end
    end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  before_filter :authenticate_user!, :except => ["facebook", :google_oauth2]

  def facebook
    # You need to implement the method below in your model
    @user = User.find_for_facebook_oauth(env["omniauth.auth"])  

    if @user.persisted?
      flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "Facebook"
      sign_in_and_redirect @user, :event => :authentication
    else
      session["devise.facebook_data"] = env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
  
  def google_oauth2
    omniauth = request.env["omniauth.auth"]
    @user = User.find_by_email(omniauth['extra']['raw_info']['email'])
    data = omniauth['extra']['raw_info']
    unless @user.blank?
      flash[:notice] = "Signed in successfully."
      sign_in_and_redirect @user, :event => :authentication
    else
      user = User.new
      user.email =  data["email"]
      user.password = Devise.friendly_token[0,20]
      user.skip_confirmation!
      if user.save
         sign_in_and_redirect user, :event => :authentication
      else
        redirect_to new_user_registration_url
      end
    end  
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper

  def devise_mapping
    Devise.mappings[:user]
  end

  def resource_name
    devise_mapping.name
  end

  def resource_class
    devise_mapping.to
  end
  
  def check_pos(id)
   if current_user
      pos = Position.where(:user_id => current_user.id, :name => id).last
      "left:"+pos.left.to_s+"px;top:"+pos.top.to_s+"px;" unless pos.blank?
   else
     ""
   end
  end
end

app/views/application/_banner_content.html.haml
.pikachoose
  %ul#pikame.jcarousel-skin-pika
    %li
      %a{:href=>"#"}
        %img{:alt => "", :src => "/assets/pict0517.jpg"}/
    %li
      %a{:href=>"#"}
        %img{:alt => "", :src => "/assets/pict0533.jpg"}/
    %li
      %a{:href=>"#"}
        %img{:alt => "", :src => "/assets/pict0538.jpg"}/
    %li
      %a{:href=>"#"}
        %img{:alt => "", :src => "/assets/pict0587.jpg"}/
    %li
      %a{:href=>"#"}
        %img{:alt => "", :src => "/assets/album/1.jpg"}/
        
        
:javascript
  $(document).ready(function(){
      $("#pikame").PikaChoose({carousel:true,carouselOptions:{wrap:'circular'}});
    
  });        

app/views/application/_header.html.haml
%ul#menu
  %li
    %a{:href => "#"} Home
  %li
    %a{:href => "#"} About Us
    %ul
      %li
        %a{:href => "#"} Environment
      %li
        %a{:href => "#"} Work Culture
      %li
        %a{:href => "#"} Board Members
  %li
    %a{:href => "#"} Technologies
    %ul
      %li
        %a{:href => "#"} ROR
        %ul
          %li
            %a{:href => "#"} Development
          %li
            %a{:href => "#"} Support
          %li
            %a{:href => "#"} Maintainence
      %li
        %a{:href => "#"} PHP
        %ul
          %li
            %a{:href => "#"} Development
          %li
            %a{:href => "#"} Support
          %li
            %a{:href => "#"} Maintainence
      %li
        %a{:href => "#"} Python
  %li
    %a{:href => "#"} Contact Us

app/views/application/_leftside_bar.html.haml
#accordion
  %h3 Section 1
  %div
    %p
      Mauris mauris ante, blandit et, ultrices a, suscipit eget
  %h3 Section 2
  %div
    %p
      Sed non urna. Donec et ante. Phasellus eu ligula. Vestibulum 
  %h3 Section 3
  %div
    %p
      Nam enim risus, molestie et, porta ac, aliquam ac, 
    %ul
      %li List item one
      %li List item two
      %li List item three
  %h3 Section 4
  %div
    %p
      Cras dictum. Pellentesque habitant morbi tristique senectus et netus
      et malesuada fames ac turpis egestas. 
      mauris vel est.
    %p
      Suspendisse eu nisl. Nullam ut libero. Integer dignissim consequat lectus.
      Class aptent taciti 

app/views/application/_login_js.html.haml
:javascript
  $(document).ready(function(){
    $('#signup').fancybox();
    
    $('#signin').fancybox();
    
    function popupCenter(url, width, height, name) {
      var wid = $(window).width();
      var left = wid/3;
      var hei = $(window).height();
      var top = hei/3;
      return window.open(url, name, "menubar=no,toolbar=no,status=no,width="+width+",height="+height+",toolbar=no,left="+left+",top="+top);
    }

    $("a.popup").click(function(e) {
      popupCenter($(this).attr("href"), 500, 400, "authPopup");
      e.stopPropagation(); return false;
    });
  });

app/views/application/_login_menu.html.haml
%ul.dropmenu
  - if user_signed_in?
    %li
      = link_to current_user.email, "#"
    %li 
      #{link_to "Sign out", signout_path, :method => :delete}
      
  - else
    %li
      %a{:href => new_user_registration_path, :id => "signup"} Signup
      =# link_to "Sign up", new_user_registration_path, :id => "signup" 
      
    %li
      %a{:href => new_user_session_path, :id => "signin"} Signin
      =# link_to "sign in", new_user_session_path, :id => "signin"
      
    %li
      = link_to "Forgot your password?", new_password_path(resource_name) if (devise_mapping.recoverable? && controller_name != 'passwords')
    - if devise_mapping.omniauthable? 
      - resource_class.omniauth_providers.each do |provider|
        %li
          = link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider), :class => "popup"
  %li
    = link_to "Default theme", root_path(:layout => "application")
  %li
    = link_to "New Layout theme", root_path(:layout => "new_layout")

app/views/application/_slider.html.erb
<div id="prevthumb"></div>
	<div id="nextthumb"></div>
	
	<a id="prevslide" class="load-item"></a>
	<a id="nextslide" class="load-item"></a>
	
	<div id="thumb-tray" class="load-item">
		<div id="thumb-back"></div>
		<div id="thumb-forward"></div>
	</div>
	
	<div id="progress-back" class="load-item">
		<div id="progress-bar"></div>
	</div>
	
	<div id="controls-wrapper" class="load-item">
		<div id="controls">
			
			<a id="play-button"><img id="pauseplay" src="assets/pause.png"/></a>
		
			<div id="slidecounter">
				<span class="slidenumber"></span> / <span class="totalslides"></span>
			</div>
			
			
			<a id="tray-button" style="display:block important;"><img id="tray-arrow" src="assets/button-tray-up.png"/></a>
			
			<ul id="slide-list"></ul>
			
		</div>
	</div>

<script type="text/javascript">
			
			jQuery(function(jQuery){
				
				jQuery.supersized({
				
					// Functionality
					slideshow               :   1,			// Slideshow on/off
					autoplay				:	1,			// Slideshow starts playing automatically
					start_slide             :   1,			// Start slide (0 is random)
					stop_loop				:	0,			// Pauses slideshow on last slide
					random					: 	0,			// Randomize slide order (Ignores start slide)
					slide_interval          :   3000,		// Length between transitions
					transition              :   6, 			// 0-None, 1-Fade, 2-Slide Top, 3-Slide Right, 4-Slide Bottom, 5-Slide Left, 6-Carousel Right, 7-Carousel Left
					transition_speed		:	1000,		// Speed of transition
					new_window				:	1,			// Image links open in new window/tab
					pause_hover             :   0,			// Pause slideshow on hover
					keyboard_nav            :   1,			// Keyboard navigation on/off
					performance				:	1,			// 0-Normal, 1-Hybrid speed/quality, 2-Optimizes image quality, 3-Optimizes transition speed // (Only works for Firefox/IE, not Webkit)
					image_protect			:	1,			// Disables image dragging and right click with Javascript
															   
					// Size & Position						   
					min_width		        :   0,			// Min width allowed (in pixels)
					min_height		        :   0,			// Min height allowed (in pixels)
					vertical_center         :   1,			// Vertically center background
					horizontal_center       :   1,			// Horizontally center background
					fit_always				:	0,			// Image will never exceed browser width or height (Ignores min. dimensions)
					fit_portrait         	:   1,			// Portrait images will not exceed browser height
					fit_landscape			:   0,			// Landscape images will not exceed browser width
															   
					// Components							
					slide_links				:	'blank',	// Individual links for each slide (Options: false, 'num', 'name', 'blank')
					thumb_links				:	1,			// Individual thumb links for each slide
					thumbnail_navigation    :   0,			// Thumbnail navigation
					slides 					:  	[			// Slideshow Images
														{image : 'http://buildinternet.s3.amazonaws.com/projects/supersized/3.2/slides/kazvan-1.jpg', title : 'Image Credit: Maria Kazvan', thumb : 'http://buildinternet.s3.amazonaws.com/projects/supersized/3.2/thumbs/kazvan-1.jpg', url : 'http://www.nonsensesociety.com/2011/04/maria-kazvan/'},
														{image : 'http://buildinternet.s3.amazonaws.com/projects/supersized/3.2/slides/kazvan-2.jpg', title : 'Image Credit: Maria Kazvan', thumb : 'http://buildinternet.s3.amazonaws.com/projects/supersized/3.2/thumbs/kazvan-2.jpg', url : 'http://www.nonsensesociety.com/2011/04/maria-kazvan/'},  
														{image : 'http://buildinternet.s3.amazonaws.com/projects/supersized/3.2/slides/kazvan-3.jpg', title : 'Image Credit: Maria Kazvan', thumb : 'http://buildinternet.s3.amazonaws.com/projects/supersized/3.2/thumbs/kazvan-3.jpg', url : 'http://www.nonsensesociety.com/2011/04/maria-kazvan/'},
														{image : 'http://buildinternet.s3.amazonaws.com/projects/supersized/3.2/slides/wojno-1.jpg', title : 'Image Credit: Colin Wojno', thumb : 'http://buildinternet.s3.amazonaws.com/projects/supersized/3.2/thumbs/wojno-1.jpg', url : 'http://www.nonsensesociety.com/2011/03/colin/'},
														{image : 'http://buildinternet.s3.amazonaws.com/projects/supersized/3.2/slides/wojno-2.jpg', title : 'Image Credit: Colin Wojno', thumb : 'http://buildinternet.s3.amazonaws.com/projects/supersized/3.2/thumbs/wojno-2.jpg', url : 'http://www.nonsensesociety.com/2011/03/colin/'},
														{image : 'http://buildinternet.s3.amazonaws.com/projects/supersized/3.2/slides/wojno-3.jpg', title : 'Image Credit: Colin Wojno', thumb : 'http://buildinternet.s3.amazonaws.com/projects/supersized/3.2/thumbs/wojno-3.jpg', url : 'http://www.nonsensesociety.com/2011/03/colin/'},
														{image : 'http://buildinternet.s3.amazonaws.com/projects/supersized/3.2/slides/shaden-1.jpg', title : 'Image Credit: Brooke Shaden', thumb : 'http://buildinternet.s3.amazonaws.com/projects/supersized/3.2/thumbs/shaden-1.jpg', url : 'http://www.nonsensesociety.com/2011/06/brooke-shaden/'},
														{image : 'http://buildinternet.s3.amazonaws.com/projects/supersized/3.2/slides/shaden-2.jpg', title : 'Image Credit: Brooke Shaden', thumb : 'http://buildinternet.s3.amazonaws.com/projects/supersized/3.2/thumbs/shaden-2.jpg', url : 'http://www.nonsensesociety.com/2011/06/brooke-shaden/'},
														{image : 'http://buildinternet.s3.amazonaws.com/projects/supersized/3.2/slides/shaden-3.jpg', title : 'Image Credit: Brooke Shaden', thumb : 'http://buildinternet.s3.amazonaws.com/projects/supersized/3.2/thumbs/shaden-3.jpg', url : 'http://www.nonsensesociety.com/2011/06/brooke-shaden/'}
												],
												
					// Theme Options			   
					progress_bar			:	1,			// Timer for each slide							
					mouse_scrub				:	0
					
				});
		    });
		    
		</script>

app/views/application/_social_pages.html.erb
<iframe src="//www.facebook.com/plugins/likebox.php?href=http%3A%2F%2Fwww.facebook.com%2Fpages%2FKrishtech%2F133762500141155&amp;width=250&amp;height=290&amp;show_faces=true&amp;colorscheme=light&amp;stream=false&amp;border_color&amp;header=true&amp;appId=430791980344979" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:250px; height:290px;" allowTransparency="true"></iframe>

<br>
<br>
<br>
<a href="https://twitter.com/nani557" class="twitter-follow-button" data-show-count="false">Follow @nani557</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>

<br>
<br>
<br>

app/views/application/get_static.html.haml
hai

app/views/application/local.html.haml
%h3 Local Address
%hr
.map
  %iframe{:frameborder => "0", :height => "350", :marginheight => "0", :marginwidth => "0", :scrolling => "no", :src => "https://maps.google.co.in/maps/ms?msa=0&msid=207662213132258852071.0004d8d11461d75904cfd&hl=en&ie=UTF8&t=m&ll=17.433149,78.440033&spn=0.003583,0.009441&z=17&output=embed", :width => "880"}
  %br/
  %small
    View
    %a{:href => "https://maps.google.co.in/maps/ms?msa=0&msid=207662213132258852071.0004d8d11461d75904cfd&hl=en&ie=UTF8&t=m&ll=17.433149,78.440033&spn=0.003583,0.009441&z=17&source=embed", :style => "color:#0000FF;text-align:left"} My Saved Places
    in a larger map

app/views/application/locations.html.haml
%h3 Locations
%hr

app/views/application/more_info.html.haml
%h3 More Information
%hr

app/views/application/php_dev.html.haml
%h3 PHP Development
%hr

app/views/application/profile.html.haml
%h3 Our Profile
%hr

app/views/application/ror_maintain.html.haml
%h3 ROR Maintainance
%hr

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Site
    = stylesheet_link_tag "normal", "green", "style", "spacegallery","pika/bottom","pika/base", "style/default","style/slidebox", "style/slidebox-my-own-style", :media => "all"
    %link{:rel=>"shortcut icon",:href=>"/assets/favicon1.gif",:type=>"image/x-icon"}/
    = javascript_include_tag "jquery","jquery.nmcDropDown", "jquery.hoverIntent", "jquery.dcmegamenu.1.3.2", "eye", "layout", "utils", "spacegallery", "jquery.jcarousel.min","jquery.pikachoose", "normal", "slidebox"
    <link rel="stylesheet" href="http://code.jquery.com/ui/1.10.2/themes/smoothness/jquery-ui.css" />
    <script src="http://code.jquery.com/ui/1.10.2/jquery-ui.js"></script>
    = csrf_meta_tags
  %body
    = render 'slidebox_content'   
    .leftbar#draggable{:style => check_pos("draggable")}
      - if devise_mapping.omniauthable? 
        - resource_class.omniauth_providers.each_with_index do |provider, i|
          %div{:class => "img#{i+1}"}
            = link_to image_tag("#{provider.to_s.gsub(" ", "_")}.jpg"), omniauth_authorize_path(resource_name, provider), :class => "popup"
      .img3= image_tag("twitter.jpg")
    .container
      #logo
        = image_tag("k.gif")
        %span Krish Tech
      #header
        .green
          %ul.mega-menu
            %li
              %a{:href => "/"} Home 
            %li
              %a{:href => "#"} About
              %ul#sortable
                %li
                  %a{:href => "#", :class => "nav-links", :id => "profile"} Profile
                %li
                  %a{:href => "#", :class => "nav-links", :id => "directors"} Board of Directors
                %li
                  %a{:href => "#", :class => "nav-links", :id => "more_info"} Other Info
            %li
              %a{:href => "#"} Technologies
              %ul
                %li
                  %a{:href => "#"} Ruby on Rails
                  %ul
                    %li
                      %a{:href => "#", :class => "nav-links", :id => "ror_dev"} Products Development
                    %li
                      %a{:href => "#", :class => "nav-links", :id => "ror_service"} Products services
                    %li
                      %a{:href => "#", :class => "nav-links", :id => "ror_maintain"} Products Maintainence
                %li
                  %a{:href => "#"} PHP
                  %ul
                    %li
                      %a{:href => "#", :class => "nav-links", :id => "php_dev"} Products Development
                %li
                  %a{:href => "#"} Python
                  %ul
                    %li
                      %a{:href => "#", :class => "nav-links", :id => "python_dev"} Products Development
            %li
              %a{:href => "#"} Contact Us
              %ul
                %li
                  %a{:href => "#", :class => "nav-links", :id => "locations"} Locations
                %li
                  %a{:href => "#", :class => "nav-links", :id => "queries"} Queries Here
                %li
                  %a{:href => "#", :class => "nav-links", :id => "local"} Local Address
            %li#links
              %a{:href => "#"} Account
              %ul
                - if user_signed_in?
                  %li
                    = link_to current_user.email, "#"
                  %li 
                    #{link_to "Sign out", signout_path, :method => :delete}
                    
                - else
                  %li
                    %a{:href => new_user_registration_path, :id => "signup"} Signup
                    =# link_to "Sign up", new_user_registration_path, :id => "signup" 
                    
                  %li
                    %a{:href => new_user_session_path+"?layout=false", :id => "signin"} Signin
                    =# link_to "sign in", new_user_session_path, :id => "signin"
                    
                  %li
                    = link_to "Forgot your password?", new_password_path(resource_name) if (devise_mapping.recoverable? && controller_name != 'passwords')
                  - if devise_mapping.omniauthable? 
                    - resource_class.omniauth_providers.each do |provider|
                      %li
                        = link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider), :class => "popup"
                %li
                  = link_to "Default theme", root_path(:layout => "application")
                %li
                  = link_to "New Layout theme", root_path(:layout => "new_layout")
                    
                    
      - flash.each do |name, msg|
        = content_tag :div, msg, :id => "flash_#{name}"     
      .content-one
        = render 'banner_content'
        .main-content
          hello 
          = yield
        .signin
          =# render 'devise/sessions/popup', :resource => User.new, :resource_name => User.new  
          =# render 'devise/registrations/register_popup', :resource => User.new, :resource_name => User.new  
      #footer
        CopyRight reserved@2013
        
        
        
:javascript
  $(document).ready(function(){
    
    jQuery('.mega-menu').dcMegaMenu({
      rowItems: '4',
      speed: 'fast',
      effect: 'slide'
    });
    
    $('#signup').fancybox();
    
    $('#signin').fancybox();
    $( "#sortable" ).sortable();
    $( ".main-content" ).resizable();
    $( "#draggable" ).draggable({
      stop: function(event, ui) {
        var off = $(this).offset();
        var nam = $(this).attr('id');
        $.ajax({
            type: "GET",
            url: '/application/extra',
            data:{"name": nam,"left": off.left,"top": off.top}
        }).done(function( msg ) {
           if ( msg == "fail") {
             alert("please sign in to save these changes!");
           }
           
        });
      }
    });
    
    
    $('ul.mega-menu li a.nav-links').click(function(){
       var id = $(this).attr('id');
      $('.main-content').load('/application/get_static?id='+id);
      return false;
    });
    
    function popupCenter(url, width, height, name) {
      var wid = $(window).width();
      var left = wid/3;
      var hei = $(window).height();
      var top = hei/3;
      return window.open(url, name, "menubar=no,toolbar=no,status=no,width="+width+",height="+height+",toolbar=no,left="+left+",top="+top);
    }

    $("a.popup").click(function(e) {
      popupCenter($(this).attr("href"), 500, 400, "authPopup");
      e.stopPropagation(); return false;
    });
  
  });

app/views/layouts/new_layout.html.haml
!!!
%html
  %head
    %title Site
    <meta http-equiv="content-type" content="text/html; charset=UTF-8" />
    = stylesheet_link_tag 'new_page', 'supersized','supersized.shutter',"style/slidebox", "style/slidebox-my-own-style",'style_1','sliderkit-core','sliderkit-demos','sliderkit-site', :media => "all"
    %link{:rel=>"shortcut icon",:href=>"/assets/favicon1.gif",:type=>"image/x-icon"}/
    <link rel="stylesheet" href="http://code.jquery.com/ui/1.10.2/themes/smoothness/jquery-ui.css" />
    <script src="http://code.jquery.com/jquery-1.9.1.js"></script>
    <script src="http://gsgd.co.uk/sandbox/jquery/easing/jquery.easing.compatibility.js"></script>
    <link rel="stylesheet" href="/resources/demos/style.css" />
    <script src="http://code.jquery.com/ui/1.10.2/jquery-ui.js"></script>
    = javascript_include_tag "supersized.3.2.7.min", "supersized.shutter.min", "slidebox", "jquery.mousewheel.min", "jquery.sliderkit.1.9.2.pack"
    = csrf_meta_tags
  %body
    %header
      %center
        .sliderkit.newslider-minimal
          .sliderkit-legend Latest news:
          .sliderkit-panels
            .sliderkit-panel
              %a{:href => "#", :title => "[link title]"} Is simply dummy text of the printing and typesetting industry...
            .sliderkit-panel
              %a{:href => "#", :title => "[link title]"} Is simply dummy text of the printing and typesetting industry...
            .sliderkit-panel
              %a{:href => "#", :title => "[link title]"} Is simply dummy text of the printing and typesetting industry...
    #account
      %a{:href => "#", :id => "accounts"} Account
      = render 'login_menu'
    .container
      .main-content
        hi
        = yield  
      .right-content
        = render 'menu'
        .social_page
          = render 'social_pages'


= render 'slider' 
:javascript
  $(function() {
    $( "#menu" ).menu();
    $( "#accordion" ).accordion();
    
  });
  
  $(document).ready(function() {
    $('#accounts').click(function() {
      $('ul.dropmenu').slideToggle();
      
    });
    
    $(".newslider-minimal").sliderkit({
    auto:true,
    circular:true,
    shownavitems:1,
    panelfx:"sliding",
    panelfxspeed:400,
    panelfxeasing:"easeOutCirc",
    mousewheel:false,
    verticalnav:true,
    verticalslide:true
    });
    
    //$('#signup').fancybox();
    
    //$('#signin').fancybox();
    
    function popupCenter(url, width, height, name) {
      var wid = $(window).width();
      var left = wid/3;
      var hei = $(window).height();
      var top = hei/3;
      return window.open(url, name, "menubar=no,toolbar=no,status=no,width="+width+",height="+height+",toolbar=no,left="+left+",top="+top);
    }

    $("a.popup").click(function(e) {
      popupCenter($(this).attr("href"), 500, 400, "authPopup");
      e.stopPropagation(); return false;
    });
  });
  